# Generated by Django 5.2.6 on 2025-10-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_area', models.CharField(max_length=100)),
                ('story_area', models.TextField()),
                ('popular_place', models.TextField()),
            ],
        ),
    ]
